name: Anubhav Patel
bio: Life doesn’t happen to you, it happens for you. 💯
description: A blog about technology and stuff related
external-image: false
picture: assets/images/anubhav.jpg
resume: true
resume-external: true
resume-url: 'https://anubhavp28.github.io/Resume/resume.pdf'
url: 'https://anubhavp28.github.io'
permalink: '/:title/'
disqus:
  shortname: anubhavp28
  categories:
    - blog
    - project
facebook: anubhavp02
twitter: anubhav0x02
github: anubhavp28
medium: anubhavp28
email: anubhavp28@gmail.com
authors:
  anubhavp:
    name: Anubhav Patel
    bio: Life doesn’t happen to you, it happens for you. 💯
    external-image: false
    picture: assets/images/anubhav.jpg
    twitter: anubhavp28
width: large
projects: false
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
